[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_egui = "0.29.0"
engine = { path = "../engine" }
tokio = { workspace = true }
uuid = { workspace = true }
