[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
bevy = { workspace = true }
engine = { path = "../engine" }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
