[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = { workspace = true }
josekit = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
